####
# Common config values
####

# Deployment annotations
deploymentAnnotations:
  deployment.kubernetes.io/revision: "4"

# Deployment self link
selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/{{ .Values.name }}

# Service self link
serviceSelfLink: /api/v1/namespaces/default/services/{{ .Values.name }}

# Metadata
creationTimestamp: "null"
generation: 1

# Pod volumes
podVolumes:
  - name: cbioportal-frontend-config-volume
    configMap:
      name: single-cell-frontend-config

# Pod Volume Mounts
podVolumeMounts:
  - name: cbioportal-frontend-config-volume
    mountPath: /cbioportal/

# Node group
nodeGroup: eks-public-cbioportal

# Pod tolerations
podTolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "eks-public-cbioportal"
    effect: "NoSchedule"

terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File

dnsPolicy: ClusterFirst

restartPolicy: Always

schedulerName: default-scheduler

securityContext: {}

terminationGracePeriodSeconds: 30

status: {}