# Name of the deployment. This is used for pods, services, etc.
name: cbioportal-backend-beta-helm

# Deployment labels
labels: []

# Pod replicas
replicas: 1

# Pod strategy
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

# Pod labels
podLabels: []

# Pod annotations
podAnnotations: []

# Primary container
container:
  configMapRef: cbioportal-beta-v6
  image: cbioportal/cbioportal:demo-rfc80-poc-web-shenandoah
  cmd: "java"
  env: []

# Readiness Probe spec. Follow the kubernetes spec definition
readinessProbe: []

# Liveness Probe spec. Follow the kubernetes spec definition
livenessProbe: []

# Container Ports
containerPorts:
  - containerPort: 8080
    protocol: TCP
  - containerPort: 8849
    protocol: TCP

# Container resources
containerResources:
  requests:
    memory: 2Gi
  limits:
    memory: 20Gi

# Service Name
serviceName: cbioportal-backend-beta-helm

# Service ports
servicePorts:
  - port: 80
    name: http
    targetPort: 8888